import "./globals.css";
import { UserProvider } from "./context/UserContext"; // 1. Import Provider

export const metadata = {
  title: "Gerbang API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
