import "./globals.css";

export const metadata = {
  title: "Gerbang API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // Tambahkan suppressHydrationWarning di sini
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
